/**
 * DEV API (beta)
 * Access DEV articles, users and other resources via API.  All endpoints that don't require authentication are CORS enabled.  Dates and date times, unless otherwise specified, must be in the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 0.7.0
 * Contact: yo@dev.to
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ArticleCreateArticle {
  title: string
    /**
     * The body of the article.  It can contain an optional front matter. For example  ```markdown --- title: Hello, World! published: true tags: discuss, help date: 20190701T10:00Z series: Hello series canonical_url: https://example.com/blog/hello cover_image: article_published_cover_image --- ```  `date`, `series` and `canonical_url` are optional. `date` is the publication date-time `series` is the name of the series the article belongs to `canonical_url` is the canonical URL of the article `cover_image` is the main image of the article  *If the markdown contains a front matter, it will take precedence on the equivalent params given in the payload.*
     */
  bodyMarkdown?: string
    /**
     * True to create a published article, false otherwise. Defaults to false
     */
  published?: boolean
    /**
     * Article series name.  All articles belonging to the same series need to have the same name in this parameter.
     */
  series?: string
  mainImage?: string
  canonicalUrl?: string
  description?: string
  tags?: Array<string>
    /**
     * Only users belonging to an organization can assign the article to it
     */
  organizationId?: number
}
