/**
 * DEV API (beta)
 * Access DEV articles, users and other resources via API.  All endpoints that don't require authentication are CORS enabled.  Dates and date times, unless otherwise specified, must be in the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 0.7.0
 * Contact: yo@dev.to
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ArticleVideoUser } from './articleVideoUser'

export interface ArticleVideo {
  _typeOf: string
  id: number
  path: string
    /**
     * The preview image of the video
     */
  cloudinaryVideoUrl: string
  title: string
  userId: number
    /**
     * The duration of the video.  If the video duration is below 1 hour, the format will be `mm:ss`, if it's 1 hour or above the format will be `h:mm:ss`.
     */
  videoDurationInMinutes: string
  user: ArticleVideoUser
}
