/**
 * DEV API (beta)
 * Access DEV articles, users and other resources via API.  All endpoints that don't require authentication are CORS enabled.  Dates and date times, unless otherwise specified, must be in the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 0.7.0
 * Contact: yo@dev.to
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ArticleFlareTag } from './articleFlareTag'
import { SharedOrganization } from './sharedOrganization'
import { SharedUser } from './sharedUser'

export interface ArticleMe {
  _typeOf: string
  id: number
  title: string
  description: string
  coverImage: string
  published: boolean
  publishedAt: Date
  tagList: Array<string>
  slug: string
  path: string
  url: string
  canonicalUrl: string
  commentsCount: number
  positiveReactionsCount: number
  pageViewsCount: number
    /**
     * Crossposting or published date time
     */
  publishedTimestamp: Date
    /**
     * The body of the article in Markdown format
     */
  bodyMarkdown: string
  user: SharedUser
  organization?: SharedOrganization
  flareTag?: ArticleFlareTag
}
