/**
 * DEV API (beta)
 * Access DEV articles, users and other resources via API.  All endpoints that don't require authentication are CORS enabled.  Dates and date times, unless otherwise specified, must be in the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 0.7.0
 * Contact: yo@dev.to
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ListingCategory = 'cfp' | 'forhire' | 'collabs' | 'education' | 'jobs' | 'mentors' | 'products' | 'mentees' | 'forsale' | 'events' | 'misc'

export const ListingCategory = {
  Cfp: 'cfp' as ListingCategory,
  Forhire: 'forhire' as ListingCategory,
  Collabs: 'collabs' as ListingCategory,
  Education: 'education' as ListingCategory,
  Jobs: 'jobs' as ListingCategory,
  Mentors: 'mentors' as ListingCategory,
  Products: 'products' as ListingCategory,
  Mentees: 'mentees' as ListingCategory,
  Forsale: 'forsale' as ListingCategory,
  Events: 'events' as ListingCategory,
  Misc: 'misc' as ListingCategory
}
