/**
 * DEV API (beta)
 * Access DEV articles, users and other resources via API.  All endpoints that don't require authentication are CORS enabled.  Dates and date times, unless otherwise specified, must be in the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 0.7.0
 * Contact: yo@dev.to
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ListingCategory } from './listingCategory'

export interface ListingUpdateClassifiedListing {
  title?: string
    /**
     * The body of the listing in Markdown format.
     */
  bodyMarkdown?: string
  category?: ListingCategory
    /**
     * Tags related to the listing.  A maximum of 8 tags are allowed and it takes precedence over `tag_list`.
     */
  tags?: Array<string>
    /**
     * Comma separated list of tags.  A maximum of 8 tags are allowed.
     */
  tagList?: string
    /**
     * Date and time of expiration.
     */
  expiresAt?: Date
    /**
     * True if users are allowed to contact the listing's owner via DEV connect, false otherwise.  Defaults to false.
     */
  contactViaConnect?: boolean
    /**
     * Geographical area or city for the listing.
     */
  location?: string
    /**
     * This param can be provided by itself to invoke some actions:  - `bump` bumps the listing and charge either the   organization or the user - `publish` publishes a draft listing - `unpublish` unpublishes a published listing  It will take priority on any other param in the payload.
     */
  action?: ListingUpdateClassifiedListing.ActionEnum
}
export namespace ListingUpdateClassifiedListing {
    export type ActionEnum = 'bump' | 'publish' | 'unpublish'
    export const ActionEnum = {
      Bump: 'bump' as ActionEnum,
      Publish: 'publish' as ActionEnum,
      Unpublish: 'unpublish' as ActionEnum
    }
}
